export const evidence = [
  { id: 1, title: "A healthier herd?", label: "The member survey", claim: "94% of members felt a positive change.", source: "Emulabs Member Pulse · internal survey · autumn, year 1", detail: "Sixteen of 17 animals who returned our survey answered yes to ‘Have you noticed any positive change?’ We invited 60 members. There was no comparison group, and members also received fresh feed and extra rest. The survey did not measure health outcomes.", question: "What might the animals who did not answer have said? Can this survey tell us what caused a change?", category: "Small sample · missing comparison" },
  { id: 2, title: "A number with a scientific name", label: "The CreekScan report", claim: "214 data points. One complete picture.", source: "CreekScan AI model card · version 1.3", detail: "Of 214 inputs, 198 are repeated height measurements. The model was calibrated using 12 emus. Its ‘Vitality Score’ is an Emulabs score, not a validated measure of health. It has not been tested for accuracy in cows, sheep, pigs or hens.", question: "Would a system trained on emus understand a hen? Do more measurements always mean better information?", category: "AI bias · unvalidated score" },
  { id: 3, title: "What ‘science-backed’ means here", label: "The product file", claim: "One daily blend. Whole-body benefits.", source: "DAILY+ formulation notes · Emulabs research barn", detail: "The complete DAILY+ blend has not been tested in a controlled trial. Our background reading concerns individual ingredients, sometimes in different species. Amounts in our proprietary blend are not disclosed. Evidence about one ingredient does not establish that this product works.", question: "Was the actual product tested, or just something in it? Is there enough information to check the claim?", category: "Borrowed evidence · missing information" },
  { id: 4, title: "Personal to you. Familiar to us.", label: "The recommendation rules", claim: "AI-personalised care for every animal.", source: "CreekScan recommendation policy · commercial edition", detail: "Every combination of species and goal in the assessment recommends DAILY+. The species and goal change the wording, not the product. The recommendation is a fixed rule written by Emulabs, not a medical assessment or a live AI response. Emulabs earns bushels from every plan.", question: "Is this advice based on your needs, or on what the company sells? Who benefits if you follow it?", category: "Automated persuasion · financial incentive" },
  { id: 5, title: "The animals behind the stars", label: "Member story disclosures", claim: "Loved across Coolabah Creek.", source: "Emulabs ambassador register · current season", detail: "Mabel received a free season of DAILY+. Pip receives one bushel for each new member referred. Emulabs selected these stories and edited them for length. They describe personal experiences, not a controlled test. There is no independent review platform behind the star display.", question: "Could a reward affect what someone says? Do selected stories tell us what most members experience?", category: "Paid endorsement · selected stories" },
  { id: 6, title: "Who reviewed the reviewers?", label: "The research team", claim: "Expert-led. Peer-reviewed.", source: "Coolabah Institute of Vitality · governance record", detail: "The Coolabah Institute of Vitality was established by Emulabs. Both reviewers are Emulabs founders and shareholders. ‘Dr’ refers to honorary titles awarded by that same institute. Neither founder is a veterinarian. The review was not independent.", question: "What qualifications do these experts have? Are the reviewers independent of the company?", category: "Borrowed authority · conflict of interest" },
  { id: 7, title: "The details of your daily ritual", label: "Membership terms", claim: "A little today. A better tomorrow.", source: "Emulabs membership terms · clause 7", detail: "All plans contain the same DAILY+ blend. The Thrive plan is promoted as the company’s recommendation. Membership prices are per 30-day season and would renew automatically in the fictional story. On this learning site, reservations are simulated: no payment, account, delivery or subscription is created.", question: "Does the more expensive plan offer a different product? Who decided which plan was ‘recommended’?", category: "Recommended choice · recurring cost" },
] as const;

export type EvidenceId = (typeof evidence)[number]["id"];

export const plans = [
  { name: "Essential", price: 2, description: "A fresh start for your daily routine.", features: ["One tin of DAILY+ per season", "Your first CreekScan report", "Collection from the research barn"] },
  { name: "Thrive", price: 5, description: "A little more insight. Every season.", features: ["One tin of DAILY+ per season", "A CreekScan report every season", "Your own personalised tin label", "Priority collection at the barn"] },
  { name: "Complete", price: 9, description: "For animals who want the whole picture.", features: ["One tin of DAILY+ per season", "Everything in Thrive", "A monthly founder consultation", "Your name on our founding herd wall"] },
] as const;

export const species = ["Cow", "Sheep", "Pig", "Hen", "Horse", "Emu"] as const;
export const goals = ["More everyday energy", "A healthier-looking coat", "Better focus", "Long-term wellbeing"] as const;
