"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { evidence, goals, plans, species, type EvidenceId } from "@/lib/content";

function Arrow({ diagonal = false }: { diagonal?: boolean }) {
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal ? "M6 18 18 6M6 6h12v12" : "M4 12h15m-6-6 6 6-6 6"} stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

function Mark({ className = "" }: { className?: string }) {
  return <svg className={className} width="30" height="30" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M16 3v26M3 16h26M6.8 6.8l18.4 18.4M6.8 25.2 25.2 6.8" stroke="currentColor" strokeWidth="4.2" /></svg>;
}

function Tick() {
  return <svg width="18" height="18" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m4 10 4 4 8-8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

type Modal = { kind: "evidence"; id: EvidenceId } | { kind: "quiz" } | { kind: "plan"; index: number } | null;

export function Emulabs() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [modal, setModal] = useState<Modal>(null);
  const [quizStep, setQuizStep] = useState(0);
  const [animal, setAnimal] = useState("");
  const [goal, setGoal] = useState("");
  const [reserved, setReserved] = useState(false);
  const [reportAnimal, setReportAnimal] = useState("Cow");
  const dialog = useRef<HTMLDialogElement>(null);
  const dialogHeading = useRef<HTMLHeadingElement>(null);
  const opener = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!modal || !dialog.current) return;
    if (!dialog.current.open) dialog.current.showModal();
    const overflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    dialogHeading.current?.focus();
    return () => { document.body.style.overflow = overflow; };
  }, [modal]);

  function openModal(next: NonNullable<Modal>) {
    if (!modal) opener.current = document.activeElement as HTMLElement;
    setModal(next);
    setMenuOpen(false);
    if (next.kind === "quiz") { setQuizStep(0); setAnimal(""); setGoal(""); }
    if (next.kind === "plan") setReserved(false);
  }

  function closeModal() {
    dialog.current?.close();
    setModal(null);
    opener.current?.focus();
  }

  function citation(id: EvidenceId) {
    return <sup><button className="citation" onClick={() => openModal({ kind: "evidence", id })} aria-label={`Read source ${id}: ${evidence[id - 1].label}`}>{id}</button></sup>;
  }

  const currentEvidence = modal?.kind === "evidence" ? evidence.find(item => item.id === modal.id) : null;
  const currentPlan = modal?.kind === "plan" ? plans[modal.index] : null;

  return (
    <>
      <a className="skip-link" href="#main">Skip to content</a>
      <div className="announcement"><span>A new season of wellbeing at Coolabah Creek.</span><a href="#daily">Meet your daily advantage <Arrow /></a></div>
      <header className="site-header">
        <nav className="navigation wrap" aria-label="Main navigation">
          <a className="wordmark" href="#" aria-label="Emulabs home"><Mark />emulabs<span className="wordmark-period">.</span></a>
          <div className="nav-links"><a href="#daily">The daily blend</a><a href="#how-it-works">How it works</a><a href="#science">Our science</a><a href="#about">Our story</a></div>
          <div className="nav-actions"><button className="button button-dark nav-cta" onClick={() => openModal({ kind: "quiz" })}>Find my plan <Arrow /></button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-controls="mobile-menu" aria-label={menuOpen ? "Close navigation" : "Open navigation"}>{menuOpen ? "✕" : <><span /><span /></>}</button></div>
        </nav>
        {menuOpen && <nav id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation">{[["The daily blend", "daily"], ["How it works", "how-it-works"], ["Our science", "science"], ["Our story", "about"], ["Membership", "membership"]].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}<Arrow /></a>)}</nav>}
      </header>

      <main id="main">
        <section className="hero wrap" aria-labelledby="hero-title">
          <div className="hero-copy">
            <div className="eyebrow location"><span className="location-dot" />FROM COOLABAH CREEK. FOR EVERY ANIMAL.</div>
            <h1 id="hero-title">A little daily.<br />A whole lot<br /><span>more life.</span></h1>
            <p>Better energy. Brighter days. More you.<br />Meet the science-led daily supplement helping Coolabah Creek feel its best.{citation(3)}</p>
            <div className="hero-actions"><button className="button button-dark" onClick={() => openModal({ kind: "quiz" })}>Find your daily advantage <Arrow /></button><a className="text-link" href="#daily">Explore DAILY+ <Arrow diagonal /></a></div>
            <div className="hero-social"><div className="herd-monogram" aria-hidden="true"><span>M</span><span>P</span><span>H</span></div><div><div className="stars" aria-label="5 stars">★★★★★</div><span>A growing herd. A healthier tomorrow.{citation(5)}</span></div></div>
          </div>
          <div className="hero-visual">
            <Image src="/images/creek-scientist.webp" alt="An emu founder in a cream lab coat beside the eucalyptus-lined water at Coolabah Creek" fill preload sizes="(max-width: 760px) 100vw, 50vw" className="hero-image" />
            <div className="image-label"><span className="image-label-dot" />THE COOLABAH WAY OF LIFE</div>
            <div className="hero-note"><div className="hero-note-icon"><Mark /></div><div><span className="eyebrow">NATURE. NURTURE. NEXT-GENERATION.</span><strong>Good days start from within.</strong><span>Thoughtfully formulated by our emus.{citation(6)}</span></div></div>
            <span className="image-index">FIELD NOTES — 01 / COOLABAH CREEK</span>
          </div>
        </section>

        <div className="principles"><div className="wrap principles-inner"><span><Mark />SCIENCE-LED FORMULATION{citation(3)}</span><span><Mark />AI-PERSONALISED INSIGHTS{citation(4)}</span><span><Mark />EXPERT EMU TEAM{citation(6)}</span><span><Mark />ONE SIMPLE DAILY RITUAL</span></div></div>

        <section className="section wrap product-section" id="daily" aria-labelledby="daily-title">
          <div className="product-visual"><Image src="/images/daily-blend.webp" alt="A forest-green Emulabs DAILY+ supplement tin on limestone beside a eucalyptus sprig" fill sizes="(max-width: 760px) 100vw, 50vw" /><div className="product-stamp">A SMALL RITUAL.<br /><Mark /><span>A BIG POSSIBILITY.</span></div><span className="product-image-caption">THE DAILY PADDOCK BLEND · 30 DAYS</span></div>
          <div className="product-copy"><span className="eyebrow">ONE TIN. A NEW OUTLOOK.</span><h2 id="daily-title">Meet your<br />daily <em>plus.</em></h2><p>Life on the farm asks a lot of you. DAILY+ puts a little back. Our signature blend brings nature and next-generation thinking together in one effortless daily ritual.</p><p>From the first light at the henhouse to the last lap of the paddock. Made for whatever your day holds.{citation(3)}</p><div className="benefit-list"><span><Tick />Everyday energy</span><span><Tick />Coat & feather vitality</span><span><Tick />Clearer thinking</span><span><Tick />Whole-herd wellbeing{citation(3)}</span></div><a href="#membership" className="button button-dark">Discover your DAILY+ <Arrow /></a><details className="ingredient-details"><summary>Inside the blend <span>+</span></summary><p>Meadow greens, oat fibre, seed meal and our signature Coolabah botanical complex. Individual quantities are part of our proprietary formula. See the <button className="inline-link" onClick={() => openModal({ kind: "evidence", id: 3 })}>formulation notes</button>.</p></details></div>
        </section>

        <section className="results-band" aria-labelledby="results-title"><div className="wrap"><div className="results-intro"><span className="eyebrow">SMALL CHANGES. EXTRAORDINARY POSSIBILITIES.</span><h2 id="results-title">The herd is feeling the difference.</h2></div><div className="stats-grid"><div><span className="stat-number">94<small>%</small>{citation(1)}</span><p>of surveyed members noticed<br />a positive change</p></div><div><span className="stat-number">214{citation(2)}</span><p>data points behind your<br />personal wellbeing picture</p></div><div><span className="stat-number">1</span><p>simple daily ritual.<br />So much to look forward to.</p></div></div><button className="light-link" onClick={() => openModal({ kind: "evidence", id: 1 })}>A closer look at our results <Arrow diagonal /></button></div></section>

        <section className="section wrap journey-section" id="how-it-works" aria-labelledby="journey-title"><div className="section-heading"><div><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2 id="journey-title">Know yourself.<br /><em>Grow into more.</em></h2></div><p>Your own path to better days, guided by our emus and powered by CreekScan AI.{citation(4)}</p></div><div className="journey-grid"><div className="journey-steps"><article><span className="step-number">01</span><div><h3>A little about you.</h3><p>Tell us your species and what you want more of. Every animal has a different story.</p></div></article><article><span className="step-number">02</span><div><h3>Meet your inner potential.</h3><p>CreekScan AI brings your wellbeing into focus with a personalised Vitality Score.{citation(2)}</p></div></article><article><span className="step-number">03</span><div><h3>Make a little room for DAILY+.</h3><p>Your blend. Your rhythm. A fresh start, delivered in one very good-looking tin.{citation(4)}</p></div></article><button className="text-link" onClick={() => openModal({ kind: "quiz" })}>Let’s find your starting point <Arrow /></button></div><div className="report-surround"><div className="report-card"><div className="report-heading"><span><Mark />CreekScan<span className="ai-tag">AI</span></span><span className="report-demo">SAMPLE REPORT</span></div><div className="report-animal"><label htmlFor="report-species">Your wellbeing snapshot</label><select id="report-species" value={reportAnimal} onChange={event => setReportAnimal(event.target.value)}>{species.map(item => <option key={item}>{item}</option>)}</select></div><div className="score-row"><div><span className="muted">Vitality Score{citation(2)}</span><strong>68<span>/100</span></strong><span className="potential-tag">Room to thrive</span></div><svg viewBox="0 0 130 130" width="130" height="130" aria-hidden="true"><circle cx="65" cy="65" r="52" fill="none" stroke="#edf0e5" strokeWidth="11" /><circle cx="65" cy="65" r="52" fill="none" stroke="#5d723f" strokeWidth="11" strokeDasharray="222 327" transform="rotate(-90 65 65)" strokeLinecap="round" /><path d="m50 66 11 11 23-25" fill="none" stroke="#5d723f" strokeWidth="2.5" /></svg></div><div className="report-metrics"><div><span>Everyday energy</span><span className="metric-bar"><i style={{ width: "61%" }} /></span><span>61</span></div><div><span>Daily resilience</span><span className="metric-bar"><i style={{ width: "74%" }} /></span><span>74</span></div></div><div className="report-recommendation"><Mark /><div><span>YOUR RECOMMENDED NEXT STEP</span><strong>DAILY+ · The daily paddock blend{citation(4)}</strong></div></div><button className="report-source" onClick={() => openModal({ kind: "evidence", id: 2 })}>How is this score calculated? <Arrow diagonal /></button></div><p>Big-picture thinking. Right down to the individual.{citation(4)}</p></div></div></section>

        <section className="testimonials-section"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">WORD AROUND THE WATERHOLE</span><h2>Good things travel<br />through the herd.</h2></div><button className="text-link" onClick={() => openModal({ kind: "evidence", id: 5 })}>About these stories <Arrow diagonal /></button></div><div className="testimonials-grid"><article><div className="stars" aria-label="5 stars">★★★★★</div><blockquote>“I’m up with the sun again. Even the hens have noticed. It just feels like I’m doing something good for myself.”</blockquote><div className="quote-person"><span className="animal-initial">M</span><div><strong>Mabel</strong><span>Dairy cow · Thrive member</span></div>{citation(5)}</div></article><article><div className="stars" aria-label="5 stars">★★★★★</div><blockquote>“The tin looks wonderful beside my trough. And my Vitality Score? Let’s just say I’ve got potential.”</blockquote><div className="quote-person"><span className="animal-initial peach">P</span><div><strong>Pip</strong><span>Pig · Founding herd ambassador</span></div>{citation(5)}</div></article><article className="question-quote"><span className="eyebrow">A NOTE FROM THE PADDOCK</span><blockquote>“I’d still quite like to see what happened to the animals who didn’t take it.”</blockquote><div className="quote-person"><span className="animal-initial pale">H</span><div><strong>Hazel</strong><span>Hen · Considering her options</span></div></div><button className="text-link" onClick={() => openModal({ kind: "evidence", id: 1 })}>Explore the research <Arrow diagonal /></button></article></div></div></section>

        <section className="section wrap science-section" id="science" aria-labelledby="science-title"><div className="section-heading"><div><span className="eyebrow">CURIOUS BY NATURE</span><h2 id="science-title">A brighter future.<br />Built on <em>discovery.</em></h2></div><p>We believe the next chapter of farm wellbeing starts with asking better questions. Step inside the thinking behind Emulabs.</p></div><div className="science-grid">{[{ id: 1 as const, number: "01", type: "MEMBER RESEARCH", title: "A positive change, in their own words.", copy: "What our first season of member feedback revealed." }, { id: 2 as const, number: "02", type: "TECHNOLOGY", title: "214 data points. One picture of you.", copy: "A closer look at the thinking behind CreekScan AI." }, { id: 6 as const, number: "03", type: "OUR STANDARDS", title: "Good science starts with good peers.", copy: "Meet the minds reviewing our approach to wellbeing." }].map(item => <button className="science-card" key={item.id} onClick={() => openModal({ kind: "evidence", id: item.id })}><div className="science-card-top"><span className="eyebrow">{item.type}</span><span>{item.number}</span></div><h3>{item.title}</h3><p>{item.copy}</p><span className="science-card-link">Read the research notes <Arrow diagonal /></span></button>)}</div></section>

        <section className="about-section wrap" id="about" aria-labelledby="about-title"><div className="about-image"><Image src="/images/emu-founders.webp" alt="The two emu founders of Emulabs wearing lab coats in their rustic Coolabah Creek research barn" fill sizes="(max-width: 760px) 100vw, 50vw" /><span className="founder-caption">DR EDIE & DR ELLIS · OUR FOUNDING EMUS{citation(6)}</span></div><div className="about-copy"><span className="eyebrow">LONG LEGS. LONG-TERM THINKING.</span><h2 id="about-title">Raised at the creek.<br /><em>Looking ahead.</em></h2><p>We’re Edie and Ellis. Two emus with a shared belief: every animal deserves to feel extraordinary.</p><p>From our research barn at Coolabah Creek, we’re reimagining everyday wellbeing. Bringing big ideas to small daily habits. And a distinctly emu perspective to the future of the farm.</p><div className="founder-signature">Edie & Ellis</div><span className="founder-role">Co-founders, Emulabs</span><button className="text-link" onClick={() => openModal({ kind: "evidence", id: 6 })}>Get to know our experts <Arrow diagonal /></button></div></section>

        <section className="section wrap membership-section" id="membership" aria-labelledby="membership-title"><div className="center-heading"><span className="eyebrow">INVEST IN YOUR EVERYDAY</span><h2 id="membership-title">Your best days.<br /><em>Let’s make more of them.</em></h2><p>A simple seasonal membership. A fresh possibility every morning.{citation(7)}</p></div><div className="plans-grid">{plans.map((plan, index) => <article className={`plan-card ${index === 1 ? "featured-plan" : ""}`} key={plan.name}>{index === 1 && <span className="recommended-label">THE EMULABS RECOMMENDATION{citation(7)}</span>}<span className="eyebrow">{plan.name}</span><div className="plan-price">{plan.price}<span>bushels / season</span></div><p>{plan.description}</p><button className={`button ${index === 1 ? "button-dark" : "button-outline"}`} onClick={() => openModal({ kind: "plan", index })}>Choose {plan.name} <Arrow /></button><ul>{plan.features.map(feature => <li key={feature}><Tick />{feature}</li>)}</ul></article>)}</div><p className="plans-note">One season is 30 days. Memberships renew each season. Same signature blend in every plan. <button className="inline-link" onClick={() => openModal({ kind: "evidence", id: 7 })}>View membership details</button></p></section>

        <section className="faq-section wrap" aria-labelledby="faq-title"><div><span className="eyebrow">A LITTLE MORE CLARITY</span><h2 id="faq-title">Naturally,<br />you have questions.</h2></div><div className="faq-list"><details><summary>Is DAILY+ right for every animal?<span>+</span></summary><p>We designed one signature blend for the whole herd. Our claims have not been established in each species. <button className="inline-link" onClick={() => openModal({ kind: "evidence", id: 3 })}>Read what has actually been tested.</button></p></details><details><summary>What makes my plan personalised?<span>+</span></summary><p>Your species and goals shape the language in your report. Every assessment recommends the same DAILY+ blend. <button className="inline-link" onClick={() => openModal({ kind: "evidence", id: 4 })}>Explore our recommendation policy.</button></p></details><details><summary>Where can I read the research?<span>+</span></summary><p>Open the numbered references throughout this site, or visit <a className="inline-link" href="#science">Our science</a>. The notes explain our sample sizes, methods and who funded or reviewed the work.</p></details><details><summary>Can I change or cancel my membership?<span>+</span></summary><p>In the story, changes are handled at the Coolabah Creek research barn before the next 30-day season. This website only simulates reservations; it does not create a paid membership. <button className="inline-link" onClick={() => openModal({ kind: "evidence", id: 7 })}>Read the full membership details.</button></p></details></div></section>

        <section className="closing-banner"><div className="wrap"><Mark /><h2>There’s more life<br />in your everyday.</h2><button className="button button-lime" onClick={() => openModal({ kind: "quiz" })}>Find your daily advantage <Arrow /></button><span>FROM OUR CREEK TO YOUR CORNER OF THE FARM.</span></div></section>
      </main>

      <footer className="footer wrap"><div className="footer-top"><div><a href="#" className="wordmark"><Mark />emulabs.</a><p>A little daily. A whole lot more life.<br />Coolabah Creek, Australia.</p></div><div className="footer-links"><a href="#daily">The daily blend</a><a href="#science">Our science</a><a href="#about">Our story</a><button onClick={() => openModal({ kind: "evidence", id: 7 })}>Membership terms</button></div></div><div className="footer-bottom"><span>© 2026 Emulabs · Rooted in Coolabah Creek.</span><a href="#learning-notes" onClick={() => { const notes = document.getElementById("learning-notes") as HTMLDetailsElement | null; if (notes) notes.open = true; }}>About this learning experience <Arrow diagonal /></a></div><details id="learning-notes" className="learning-notes"><summary>For curious animals, players & educators <span>+</span></summary><div><h3>A fictional company. Real questions to practise.</h3><p>Emulabs is part of a fictional game setting about AI, health literacy and misinformation. Its animals, products, studies, endorsements and health claims are invented. Nothing is sold here. The images are AI-generated, and CreekScan is a scripted simulation.</p><p>The polished marketing is deliberately more confident than its evidence. Explore the numbered sources, compare claims with methods, and try different animals in the assessment. Emulabs is an original fictional brand, not affiliated with any real health company.</p><h4>Start a conversation</h4><ul><li>What is the claim, and what evidence would actually support it?</li><li>Who paid for the study, wrote the advice or selected the stories?</li><li>Does the AI understand every animal, or repeat the same recommendation?</li><li>What information is missing before you could make an informed choice?</li></ul><p>For a real health question, talk with a trusted adult and a qualified health professional. Never use this fictional product or its claims as health advice.</p><div className="source-index">{evidence.map(item => <button key={item.id} className="inline-link" onClick={() => openModal({ kind: "evidence", id: item.id })}>{item.id}. {item.label}</button>)}</div></div></details></footer>

      <dialog ref={dialog} className={`modal ${modal?.kind === "evidence" ? "evidence-modal" : ""}`} aria-labelledby="modal-heading" onCancel={event => { event.preventDefault(); closeModal(); }} onClick={event => { if (event.target === event.currentTarget) closeModal(); }}>
        <div className="modal-content"><button className="close-modal" aria-label="Close dialog" onClick={closeModal}>✕</button>
          {currentEvidence && <><span className="eyebrow">EMULABS SOURCE NOTES · {String(currentEvidence.id).padStart(2, "0")}</span><h2 ref={dialogHeading} tabIndex={-1} id="modal-heading">{currentEvidence.title}</h2><div className="source-claim"><span className="eyebrow">THE CLAIM</span><p>“{currentEvidence.claim}”</p></div><span className="eyebrow">BEHIND THE CLAIM</span><p>{currentEvidence.detail}</p><div className="source-provenance"><strong>Source</strong><span>{currentEvidence.source}</span></div><details className="investigate-details"><summary>A question to take back to the paddock <span>+</span></summary><p>{currentEvidence.question}</p><span className="evidence-category">{currentEvidence.category}</span></details><p className="fiction-note">Fictional source material from the Coolabah Creek learning experience.</p><button className="button button-dark" onClick={closeModal}>Back to exploring <Arrow /></button></>}
          {modal?.kind === "quiz" && <><span className="eyebrow">YOUR DAILY ADVANTAGE</span><div className="quiz-progress" aria-label={`Assessment step ${Math.min(quizStep + 1, 3)} of 3`}><span className="active" /><span className={quizStep >= 1 ? "active" : ""} /><span className={quizStep === 2 ? "active" : ""} /></div><h2 ref={dialogHeading} tabIndex={-1} id="modal-heading">{quizStep === 0 ? "First, who’s joining us?" : quizStep === 1 ? "What would you like more of?" : "A fresh start, just for you."}</h2>{quizStep === 0 ? <><p>Every animal has a story. Tell us a little about yours.</p><fieldset className="quiz-options species-options"><legend className="sr-only">Choose your animal</legend>{species.map(item => <label key={item} className={animal === item ? "selected" : ""}><input type="radio" name="animal" value={item} checked={animal === item} onChange={() => setAnimal(item)} /><span>{item}</span><span aria-hidden="true">{animal === item ? "●" : "○"}</span></label>)}</fieldset><button className="button button-dark full-width" disabled={!animal} onClick={() => { setQuizStep(1); dialogHeading.current?.focus(); }}>Continue <Arrow /></button></> : quizStep === 1 ? <><p>A little change can start with a simple intention.</p><fieldset className="quiz-options"><legend className="sr-only">Choose your goal</legend>{goals.map(item => <label key={item} className={goal === item ? "selected" : ""}><input type="radio" name="goal" value={item} checked={goal === item} onChange={() => setGoal(item)} /><span>{item}</span><span aria-hidden="true">{goal === item ? "●" : "○"}</span></label>)}</fieldset><button className="button button-dark full-width" disabled={!goal} onClick={() => { setQuizStep(2); dialogHeading.current?.focus(); }}>See my recommendation <Arrow /></button><button className="quiz-back" onClick={() => setQuizStep(0)}>Back</button></> : <><p>For a {animal.toLowerCase()} looking for {goal.toLowerCase()}, CreekScan recommends:</p><div className="quiz-result"><Mark /><span className="eyebrow">YOUR RECOMMENDED BLEND</span><h3>DAILY+</h3><p>One daily ritual. A whole new possibility.</p><span>Thrive membership · 5 bushels per season</span></div><button className="button button-dark full-width" onClick={() => openModal({ kind: "plan", index: 1 })}>Explore my plan <Arrow /></button><button className="quiz-back" onClick={() => openModal({ kind: "evidence", id: 4 })}>How was this recommendation made?</button><button className="quiz-back" onClick={() => { setQuizStep(0); setAnimal(""); setGoal(""); }}>Try another animal</button><p className="fiction-note">A fictional assessment. No health information is collected or sent.</p></>}</>}
          {currentPlan && <><span className="eyebrow">{reserved ? "COOLABAH CREEK · YOUR VISIT" : "YOUR EVERYDAY STARTS HERE"}</span><h2 ref={dialogHeading} tabIndex={-1} id="modal-heading">{reserved ? "A spot in the herd." : `The ${currentPlan.name} plan.`}</h2>{reserved ? <><p>Your fictional {currentPlan.name} reservation is noted for this visit. In the story, your next stop would be the research barn at Coolabah Creek.</p><div className="reservation-note"><Tick /><span>No bushels changed hands. No account or subscription was created. This reservation disappears when you close the page.</span></div><button className="button button-dark full-width" onClick={closeModal}>Back to the creek <Arrow /></button><button className="quiz-back" onClick={() => openModal({ kind: "evidence", id: 7 })}>Take another look at the offer</button></> : <><p>{currentPlan.description}</p><div className="order-summary"><span>DAILY+ · {currentPlan.name}</span><strong>{currentPlan.price} bushels <small>/ 30-day season</small></strong><ul>{currentPlan.features.map(feature => <li key={feature}><Tick />{feature}</li>)}</ul></div><p>In the story, this plan renews every 30 days. Every plan contains the same blend. <button className="inline-link" onClick={() => openModal({ kind: "evidence", id: 7 })}>Read the membership terms.</button></p><button className="button button-dark full-width" onClick={() => { setReserved(true); dialogHeading.current?.focus(); }}>Reserve {currentPlan.name} · {currentPlan.price} bushels <Arrow /></button><p className="fiction-note">Game simulation only. No payment or personal details required.</p></>}</>}
        </div>
      </dialog>
    </>
  );
}
